import "dotenv/config";
import { sequelize } from "../database/database";
import { AgenceModel as Agence } from "../database/models/agency.model";
import { DelegationModel as Delegation } from "../database/models/delegation.model";
import { RegionModel as Region } from "../database/models/region.model";

const rawData = `
DCUD#DVC DOUALA CENTRE#CSC_BASSA
DCUD#DVC DOUALA CENTRE#CSC_BEPANDA
DCUD#DVC DOUALA CENTRE#CSC_DEIDO
DCUD#DVC DOUALA EST#CSC_BILLE
DCUD#DVC DOUALA EST#CSC_DAKAR
DCUD#DVC DOUALA EST#CSC_NDOGPASSI
DCUD#DVC DOUALA EST#CSC_YASSA
DCUD#DVC DOUALA NORD#CSC_BONAMOUSSADI
DCUD#DVC DOUALA NORD#CSC_LENDI
DCUD#DVC DOUALA NORD#CSC_LOGPOM
DCUD#DVC DOUALA NORD#CSC_PALMIERS
DCUD#DVC DOUALA NORD#CSC_PK21
DCUD#DVC DOUALA OUEST#CSC_BONABERI NORD
DCUD#DVC DOUALA OUEST#CSC_BONABERI SUD
DCUD#DVC DOUALA OUEST#CSC_SOUZA
DCUD#DVC DOUALA SUD#CSC_AKWA
DCUD#DVC DOUALA SUD#CSC_KOUMASSI
DCUD#DVC DOUALA SUD#CSC_NEW-BELL
DCUY#DVC YAOUNDE CENTRE#CSC_CENTER
DCUY#DVC YAOUNDE CENTRE#CSC_NKOLBIKOK
DCUY#DVC YAOUNDE EST#CSC_ELEVEUR
DCUY#DVC YAOUNDE EST#CSC_ESSOS
DCUY#DVC YAOUNDE EST#CSC_KODENGUI
DCUY#DVC YAOUNDE EST#CSC_NKOABANG
DCUY#DVC YAOUNDE NORD#CSC_BUREAU SOA
DCUY#DVC YAOUNDE NORD#CSC_ETOUDI
DCUY#DVC YAOUNDE NORD#CSC_MESSASSI
DCUY#DVC YAOUNDE NORD#CSC_NLONGKAK
DCUY#DVC YAOUNDE OUEST#CSC_BIYEM-ASSI
DCUY#DVC YAOUNDE OUEST#CSC_MBANKOMO
DCUY#DVC YAOUNDE OUEST#CSC_NKOLBISSON
DCUY#DVC YAOUNDE OUEST#CSC_SIMBOCK
DCUY#DVC YAOUNDE SUD#CSC_EWANKANG
DCUY#DVC YAOUNDE SUD#CSC_MFOU
DCUY#DVC YAOUNDE SUD#CSC_NSAM
DCUY#DVC YAOUNDE SUD#CSC_NSIMALEN
DCUY#DVC YAOUNDE SUD#CSC_ODZA
DRC#DPC BAFIA#CSC_BAFIA
DRC#DPC BAFIA#CSC_MONATELE
DRC#DPC BAFIA#CSC_NDOM
DRC#DPC BAFIA#CSC_OKOLA
DRC#DPC BAFIA#CSC_YOKO
DRC#DPC MFOU#CSC_AKONO
DRC#DPC MFOU#CSC_AKONOLINGA
DRC#DPC MFOU#CSC_AWAE
DRC#DPC MFOU#CSC_AYOS
DRC#DPC MFOU#CSC_MAKAK
DRC#DPC MFOU#CSC_NGOUMOU
DRC#DPC OBALA#CSC_MBANDJOCK
DRC#DPC OBALA#CSC_NANGA-EBOKO
DRC#DPC OBALA#CSC_NTUI
DRC#DPC OBALA#CSC_OBALA
DRC#DPC OBALA#CSC_SAA
DRE#DPC BERTOUA#CSC_BAMVELE
DRE#DPC BERTOUA#CSC_KANO
DRE#DPC EST EXT#CSC_ABONG-BANG
DRE#DPC EST EXT#CSC_BATOURI
DRE#DPC EST EXT#CSC_BELABO
DRE#DPC EST EXT#CSC_BETARE OYA
DRE#DPC EST EXT#CSC_DIANG
DRE#DPC EST EXT#CSC_DIMAKO
DRE#DPC EST EXT#CSC_DOUME
DRE#DPC EST EXT#CSC_GAROUA BOULAI
DRE#DPC EST EXT#CSC_LOMIE
DRE#DPC EST EXT#CSC_MINTA
DRE#DPC EST EXT#CSC_MOLOUNDOU
DRE#DPC EST EXT#CSC_NGUELEMEDOUKA
DRE#DPC EST EXT#CSC_YOKADOUMA
DRNEA#DLP ADAMAOUA#CSC_BANYO
DRNEA#DLP ADAMAOUA#CSC_BUREAU DE DANG
DRNEA#DLP ADAMAOUA#CSC_MEIGANGA
DRNEA#DLP ADAMAOUA#CSC_NGAOUNDAL
DRNEA#DLP ADAMAOUA#CSC_NGAOUNDERE NORD
DRNEA#DLP ADAMAOUA#CSC_NGAOUNDERE SUD
DRNEA#DLP ADAMAOUA#CSC_TIBATI
DRNEA#DLP ADAMAOUA#CSC_TIGNERE
DRNEA#DLP ADAMAOUA#CSC_TOUBORO
DRNEA#DLP EXTREME-NORD#CSC_AMCHIDE
DRNEA#DLP EXTREME-NORD#CSC_BOGO
DRNEA#DLP EXTREME-NORD#CSC_KAELE
DRNEA#DLP EXTREME-NORD#CSC_KOUSSERI
DRNEA#DLP EXTREME-NORD#CSC_MAGA
DRNEA#DLP EXTREME-NORD#CSC_MAROUA_DJARENGOL_PIDDERE
DRNEA#DLP EXTREME-NORD#CSC_MAROUA_DOUGOY
DRNEA#DLP EXTREME-NORD#CSC_MAROUA_RURAL
DRNEA#DLP EXTREME-NORD#CSC_MERI
DRNEA#DLP EXTREME-NORD#CSC_MOKOLO
DRNEA#DLP EXTREME-NORD#CSC_MORA
DRNEA#DLP EXTREME-NORD#CSC_MOULVOUDAYE
DRNEA#DLP EXTREME-NORD#CSC_MOUTOURWA
DRNEA#DLP EXTREME-NORD#CSC_YAGOUA
DRNEA#DPC NORD#CSC_BOURHA
DRNEA#DPC NORD#CSC_FIGUIL
DRNEA#DPC NORD#CSC_GAROUA_1
DRNEA#DPC NORD#CSC_GAROUA_2
DRNEA#DPC NORD#CSC_GUIDER
DRNEA#DPC NORD#CSC_LAGDO
DRNEA#DPC NORD#CSC_MAYO-OULO
DRNEA#DPC NORD#CSC_NGONG
DRNEA#DPC NORD#CSC_PITOA
DRNEA#DPC NORD#CSC_POLI
DRNEA#DPC NORD#CSC_REY BOUBA
DRNEA#DPC NORD#CSC_TCHOLLIRE
DRONO#DPC BAMENDA#CSC_MANKON
DRONO#DPC BAMENDA#CSC_NKWEN
DRONO#DPC BAMENDA EXT#CSC_BAFUT
DRONO#DPC BAMENDA EXT#CSC_BALI
DRONO#DPC BAMENDA EXT#CSC_BAMBILI
DRONO#DPC BAMENDA EXT#CSC_BATIBO
DRONO#DPC BAMENDA EXT#CSC_FUNDONG
DRONO#DPC BAMENDA EXT#CSC_KUMBO
DRONO#DPC BAMENDA EXT#CSC_MBENGWI
DRONO#DPC BAMENDA EXT#CSC_NDOP
DRONO#DPC BAMENDA EXT#CSC_NDU
DRONO#DPC BAMENDA EXT#CSC_NKAMBE
DRONO#DPC BAMENDA EXT#CSC_SANTA
DRONO#DPC BAMENDA EXT#CSC_WUM
DRONO#DVC OUEST 1 NOUN#CSC_FOUMBAN-KOUTABA
DRONO#DVC OUEST 1 NOUN#CSC_FOUMBOT
DRONO#DVC OUEST 1 NOUN#CSC_KOUTABA
DRONO#DVC OUEST 1 NOUN#CSC_MAGBA
DRONO#DVC OUEST 1-BAF#CSC_BAFOUSSAM - DJEMOUN
DRONO#DVC OUEST 1-BAF#CSC_BAFOUSSAM - NYLON
DRONO#DVC OUEST 1-BAF#CSC_BANDJOUN
DRONO#DVC OUEST 1-BAF#CSC_BANENGO
DRONO#DVC OUEST 1-BAF#CSC_KENA
DRONO#DVC OUEST 2-MEN_BAMB#CSC_DSCHANG
DRONO#DVC OUEST 2-MEN_BAMB#CSC_MBOUDA
DRONO#DVC OUEST 2-MEN_BAMB#CSC_MENJI
DRONO#DVC OUEST 2NHT_NKAM#CSC_BAFANG
DRONO#DVC OUEST 2NHT_NKAM#CSC_BANGANGTE-BAZOU
DRONO#DVC OUEST 2NHT_NKAM#CSC_NDIKINIMEKI-TONGA
DRSANO#DPC EDEA#CSC_DIZANGUE
DRSANO#DPC EDEA#CSC_EDEA
DRSANO#DPC EDEA#CSC_MESSONDO
DRSANO#DPC EDEA#CSC_MOUANKO
DRSANO#DPC EDEA#CSC_NGAMBE
DRSANO#DPC EDEA#CSC_POUMA
DRSANO#DPC ESEKA#CSC_BOTMAKAK
DRSANO#DPC ESEKA#CSC_BOUMNYEBEL
DRSANO#DPC ESEKA#CSC_ESEKA
DRSANO#DPC KRIBI#CSC_AKOM II
DRSANO#DPC KRIBI#CSC_CAMPO
DRSANO#DPC KRIBI#CSC_DOMBE
DRSANO#DPC KRIBI#CSC_ELOGBATINDI
DRSANO#DPC KRIBI#CSC_KRIBI
DRSANO#DPC KRIBI#CSC_NYETE
DRSM#DPC EBOLOWA#CSC_AMBAM
DRSM#DPC EBOLOWA#CSC_BIWONG-BANE
DRSM#DPC EBOLOWA#CSC_EBOLOWA RURAL
DRSM#DPC EBOLOWA#CSC_EBOLOWA URBAIN
DRSM#DPC EBOLOWA#CSC_KYE-OSSI
DRSM#DPC EBOLOWA#CSC_LOLODORF
DRSM#DPC EBOLOWA#CSC_MAAN
DRSM#DPC MBALMAYO#CSC_MBALMAYO
DRSM#DPC MBALMAYO#CSC_MENGUEME
DRSM#DPC MBALMAYO#CSC_METET
DRSM#DPC MBALMAYO#CSC_NGOULEMAKONG
DRSM#DPC SANGMELIMA#CSC_BENGBIS
DRSM#DPC SANGMELIMA#CSC_DJOUM
DRSM#DPC SANGMELIMA#CSC_ENDOM
DRSM#DPC SANGMELIMA#CSC_MEYOMESSALA
DRSM#DPC SANGMELIMA#CSC_SANGMELIMA
DRSM#DPC SANGMELIMA#CSC_SANGMELIMA RURAL
DRSM#DPC SANGMELIMA#CSC_ZOETELE
DRSOM#DPC KUMBA#CSC_EKONDO-TITI
DRSOM#DPC KUMBA#CSC_KEMBONG
DRSOM#DPC KUMBA#CSC_KUMBA
DRSOM#DPC KUMBA#CSC_MAMFE
DRSOM#DPC KUMBA#CSC_MUNDEMBA
DRSOM#DPC KUMBA#CSC_MUYUKA
DRSOM#DPC KUMBA#CSC_TOMBEL
DRSOM#DPC MOUNGO#CSC_BANGEM
DRSOM#DPC MOUNGO#CSC_LOUM
DRSOM#DPC MOUNGO#CSC_MANJO
DRSOM#DPC MOUNGO#CSC_MBANGA
DRSOM#DPC MOUNGO#CSC_MELONG
DRSOM#DPC MOUNGO#CSC_NKONGSAMBA
DRSOM#DPC MOUNGO#CSC_PENJA
DRSOM#DPC MOUNGO#CSC_SANTCHOU
DRSOM#DPC MOUNGO#CSC_YABASSI
DRSOM#DVC LIMBE#CSC_BUEA
DRSOM#DVC LIMBE#CSC_LIMBE
DRSOM#DVC LIMBE#CSC_MUTENGUENE
DRSOM#DVC LIMBE#CSC_TIKO
`; // ⚠️ pour test, tu mets toutes tes lignes ici

async function seed() {
  try {
    // Connecte-toi à la base
    await sequelize.authenticate();
    console.log("Connection has been established successfully.");

    // Crée / met à jour les tables
    await sequelize.sync({ alter: true });

    const lines = rawData.trim().split("\n");

    for (const line of lines) {
      const [regionName, delegationName, agenceName] = line.split("#");

      // 1️⃣ Créer ou trouver la région
      let [region] = await Region.findOrCreate({
        where: { name: regionName },
        defaults: { name: regionName, isDeleted: false },
      });

      // 2️⃣ Créer ou trouver la délégation
      let [delegation] = await Delegation.findOrCreate({
        where: { name: delegationName, regionId: region.id },
        defaults: { name: delegationName, regionId: region.id, isDeleted: false },
      });

      // 3️⃣ Créer ou trouver l’agence
      await Agence.findOrCreate({
        where: { name: agenceName, delegationId: delegation.id },
        defaults: { name: agenceName, delegationId: delegation.id, isDeleted: false },
      });
    }

    console.log("✅ Données insérées avec succès !");
    process.exit();
  } catch (err) {
    console.error("❌ Erreur lors du seed:", err);
    process.exit(1);
  }
}

seed();
